[features]
seeds = false
skip-lint = false
[programs.localnet]
payble = "5FePENF8rtAjLxiejbZ1bFKLC1GfBjYGiUtWTsdDtfZz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/samirj523/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
